dist: trusty
language: ruby
rvm:
  - 2.4.4
  - 2.5.1
  - ruby-head
env:
  - DRIVER=google-chrome TZ=Europe/Berlin
  - DRIVER=firefox TZ=Europe/Berlin MOZ_HEADLESS=1

matrix:
    fast_finish: true
    allow_failures:
      - rvm: ruby-head
      - env: DRIVER=firefox TZ=Europe/Berlin MOZ_HEADLESS=1
before_install:
  - if [[ "$DRIVER" == "google-chrome" ]]; then wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -; fi
  - if [[ "$DRIVER" == "google-chrome" ]]; then echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list; fi
  - if [[ "$DRIVER" == "google-chrome" ]]; then sudo apt-get update -qq && sudo apt-get install -qq -y google-chrome-stable; fi
  - if [[ "$DRIVER" == "firefox" ]]; then sudo apt-get update -qq && sudo apt-get install -qq -y firefox; fi
  - if [[ "$DRIVER" == "firefox" ]]; then wget -q https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz; fi
  - if [[ "$DRIVER" == "firefox" ]]; then tar zxf geckodriver-v0.21.0-linux64.tar.gz; fi
  - if [[ "$DRIVER" == "firefox" ]]; then sudo mv geckodriver /usr/local/bin/; fi
  - gem install bundler
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - cd spec/test_app
  - bundle install --jobs=3 --retry=3
  - bundle exec rails db:setup
  - cd ../../
  - if [[ "$DRIVER" == "google-chrome" ]]; then chromedriver-update; fi
  - if [[ "$DRIVER" == "google-chrome" ]]; then ls -lR ~/.chromedriver-helper/; fi
  - if [[ "$DRIVER" == "google-chrome" ]]; then chromedriver --version; fi
  - if [[ "$DRIVER" == "google-chrome" ]]; then google-chrome --version; fi
  - if [[ "$DRIVER" == "google-chrome" ]]; then which chromedriver; fi
  - if [[ "$DRIVER" == "google-chrome" ]]; then which google-chrome; fi
  - if [[ "$DRIVER" == "firefox" ]]; then firefox --version; fi
  - if [[ "$DRIVER" == "firefox" ]]; then geckodriver --version; fi
  - if [[ "$DRIVER" == "firefox" ]]; then which firefox; fi
  - if [[ "$DRIVER" == "firefox" ]]; then which geckodriver; fi
script: bundle exec rspec
