language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-19mode
script:
  - bundle exec rake test_app
  - bundle exec rake
gemfile:
  - gemfiles/react_13.gemfile
  - gemfiles/react_14.gemfile
  - gemfiles/react_15.gemfile
