language: ruby
rvm:
  - ruby
services:
  - mysql
env:
  - HYPER_DEV_GEM_SOURCE="https://gems.ruby-hyperloop.org"
before_install:
  - export
  - gem install bundler
before_script:
  - cd spec/test_app
  - bundle update
  - rails db:setup
  - cd ../../
script: bundle exec rspec
gemfile:
  - gemfiles/opal_0_10_react-rails_2_3.gemfile
  - gemfiles/opal_0_10_react-rails_2_4.gemfile
  - gemfiles/opal_0_11_react-rails_2_4.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/opal_0_11_react-rails_2_4.gemfile