dist: trusty
language: ruby
rvm:
  - 2.4.4
  - 2.5.1
  - ruby-head
env:
  - DRIVER=travis TZ=Europe/Berlin
  - DRIVER=beheaded TZ=Europe/Berlin
before_install:
  - if [[ "$DRIVER" == "travis" ]]; then wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -; fi
  - if [[ "$DRIVER" == "travis" ]]; then echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list; fi
  - if [[ "$DRIVER" == "travis" ]]; then sudo apt-get update -qq && sudo apt-get install -qq -y google-chrome-stable; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then tar zxf geckodriver-v0.19.1-linux64.tar.gz; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then sudo mv geckodriver /usr/local/bin/; fi
  - gem install bundler
before_script:
  - cd spec/test_app
  - bundle install --jobs=3 --retry=3
  - bundle exec rails db:setup
  - cd ../../
  - if [[ "$DRIVER" == "travis" ]]; then chromedriver-update; fi
  - if [[ "$DRIVER" == "travis" ]]; then ls -lR ~/.chromedriver-helper/; fi
  - if [[ "$DRIVER" == "travis" ]]; then chromedriver --version; fi
  - if [[ "$DRIVER" == "travis" ]]; then google-chrome --version; fi
  - if [[ "$DRIVER" == "travis" ]]; then which chromedriver; fi
  - if [[ "$DRIVER" == "travis" ]]; then which google-chrome; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then firefox --version; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then geckodriver --version; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then which firefox; fi
  - if [[ "$DRIVER" == "beheaded" ]]; then which geckodriver; fi
script: bundle exec rspec
